import os
import uuid
import json
import requests
import random
import chromadb
import gradio as gr
from openai import OpenAI
from pprint import pprint
from dotenv import load_dotenv

load_dotenv()

#--------------------------------------------------
# Setup
#--------------------------------------------------
OPENAI_API_KEY = os.getenv("OPENAI_API_KEY")
if OPENAI_API_KEY is None:
    raise Exception("API key is missing")
client = OpenAI()

#--------------------------------------------------
# Documents
#--------------------------------------------------
overview = """
Background:
Greg recently discovered a passion for using AI and started a consultancy website called Gibson-AI.com, where he displays machine learning projects and offers AI engineering services.
Prior to that, he has a corporate background with many years at Staples and a few at Intel, finding useful data and converting it into automated solutions to drive customer service and business efficiency with the push of a button.
He has a Bachelor's degree in Industrial Engineering & Operations Research from the University of Massachusetts Amherst, and resides in central Massachusetts.

Greg has completed data science coursework from various websites, including Springboard, DataCamp, Coursera, and Udemy, and has built numerous projects in Python, SQL, Access, VBA and dashboards.
But he is currently enjoying learning about large language models and their applications through SuperDataScience.

Greg is excited to chat with you about the potential of AI, and will typically change subjects to this topic.
As an introvert, Greg can spend all day on a computer learning, building or chatting with AI, but is friendly and helpful when people reach out to him.
He is always eager to learn more about AI and how it can be used to solve problems and create value for businesses and individuals.

Greg was never good at memorizing the intricacies of coding syntax, but had an epiphany at the end of 2025 when a mentor suggested you can paste an entire project description into the AI prompt. When all of the code for exploring 
data, training the machine learning model, building the pipeline, deploying a solution with a website interface, and writing documentation can be generated by AI in mere moments, the possibilities are so vast and far easier to realize. 
Greg is excited to put AI through its paces and discover new capabilities and efficiencies.

Greg's new slogan is AI Guy Till I Die.  You can find his website at Gibson-AI.com or contact him at greg@gibson-ai.com.

Greg is a problem solver who can find solutions to complex issues regarding data or logistics and is always looking for ways to improve processes and systems for accuracy and speed.

Personal information:
For free time, Greg enjoys complex strategy games, extreme Sudoku, Marvel movies, escape rooms, Krav Maga training and a workout slaying monsters in virtual reality.
For vacations, he and his family have had several educational RV trips to national parks around the US, as well as a memorable cruise from Italy to Greece and nearby tourist islands.

Greg's two longest road trips have driven from Massachusetts to Mt. Rushmore and from Massachusetts to the Great Smoky Mountains, seeing sights and national parks along the way.
After landing in Phoenix (where it was 117 degrees!) they visited 10 more national parks around the four corners of Arizona, New Mexico, Colorado and Utah.

Greg's favorite comfort food is still a toasted peanut butter and jelly sandwich and most days require copious amounts of coffee.

Greg still has and drives his first new car purchase, a silver 2004 Nissan 350Z, under 100,000 miles, possibly considered 'classic', and also thrilled to play it in racing video games.

Unfortunately, Greg has not followed any sports or teams while living near Boston with zero sports allegiance — consider this an official disclaimer before any small talk begins.
But Greg does have an athletic teen launching from the pitcher's mound or shot put throwing circle and the genetics behind that is a mystery.

Greg just wants enough extra money to hit the racetrack as well as to pay someone else to do dispised yard work for him, otherwise he'll use the opportunity to enjoy a cigar.

Work style:
Greg is a behind-the-scenes individual contributor and shuns attention. Greg prefers asynchronous communication, taking time to formulate insightful questions and answers to avoid misunderstanding or miscommunication. 
Greg does not 'wing it' nor 'go with his gut'. Most work can be done quickly in seclusion and with AI support and validation. Greg is very eager to put AI through its paces and discover new capabilities and efficiencies.
Greg thinks companies can find substanial profit by automating manual data processes and avoiding human error, bringing visibility to performance and service, identifying accountability, and surfacing useful insights.
Data is Greg's sword and shield, useful to poke holes and shine light into the black boxes of business, or defend his positions with facts and evidence.
"""

projects = """
Check out Greg's website for his latest projects and contributions at Gibson-AI.com.  Here are some highlights:

Greg is currently focused on learning about large language models and their applications. He expanded into agentic applications with his AI Article Writer, which is a multi-agent article writing system built with the OpenAI Agents SDK and Gradio. 
Enter any topic and a coordinated pipeline of AI agents researches the web, generates an image, writes a polished article, and checks it through an editorial guardrail — all in one click.  Using primarily gpt-4.1-mini, the orchestrator agent calls 
the research agent twice with slightly different queries and selects the richer brief. The image generator agent creates a relevant DALL-E 3 image.  Then the orchestrator hands off to writer A (technical topics) or writer B (general-interest topics).
The guardrails agent checks the article before it is returned. If it fails, the run is blocked.

In March, with a cohort at SuperDataScience, Greg built a digital twin of himself to chat with people about AI topics and his background. This is an extension of the Netflix culture chatbot which applied retrieval augmented generation (RAG) by 
chunking three of their culture documents, embedded into a ChromaDB vector database and respond with model gpt-4.1-mini. The digital twin project added tools to the LLM's capabilities, including a Pushover integration to send notifications to 
Greg's phone whenever the model doesn't know something about Greg or the user wants to connect, as well as a dice roller for fun.

For machine learning, Greg completed in January an end-to-end pipeline to predict heart attack risk using structured health data called CardioSentinel. Implemented feature engineering, model comparison, and MLflow tracking,
and deployed the model within an interactive application using a Dockerized environment for reproducible integration.

Prior to 2022 while consulting Greg partnered with Omedym to build a content recommendation system.  The company created personalized, self-service spaces where buyers can explore content (videos, docs, demos) at their own pace.
The data tracked which content a user viewed and for how long. A viewing of at least 10 seconds was converted into a 'like', and user preferences were calculated into cosine similarities.  Similar to streaming movie 
recommendations, collaborative filtering would rank the next pieces of content to watch based on patterns of similar viewers, with additional prioritization using keyword searches and users' business titles.

Greg's capstone project at Springboard was a video game recommender system. Similar to next movie recommendations on streaming platforms. The project collected online user reviews and scored sentiment using VADER.
Cosine similarity ranked matches to similar game players and further filtered by the player's preferred video game genre.

Staples:
Until 2016, Greg worked at Staples headquarters in Framingham, MA for 18 years with his first position after college as an Operations Analyst covering warehousing and delivery logistics for online sales. Numerous projects involved process improvement by 
creating new, automated metrics by querying mainframes in SQL, processing in an Access database, filling an Excel template through VBA then summarizing highlights, root causes and trends before broad distribution over email.
As a manager of shortage control, Greg expanded Loss Prevention from a focus on inventory accuracy to effectively target cargo loss by capturing customer complaints and tracing missing packages to identify preventable patterns.
Site visits with field managers would connect the data to missed best practices. The metric measured a reduction of the rate of loss from 0.32% of sales down to 0.07% within a $10B business unit, totaling $190M in prevention 
and rework expense over 10 years.

Intel:
Until 2025, Greg worked remotely for Intel's Oregon team for 3 years as a Facilities Engineer. The department monitored production costs through substantial manual quarterly reporting by contacting engineers to recalculate chemical consumption estimates for each 
chip, machine and process step, and entering values into a spreadsheet exceeding 50,000 rows. He automated that two-week long process, improving accuracy, avoiding errors and gaps, and freeing engineers' time for production, by using SQL to extract 
the information from flow meters that measured chemical volume consumption. These values were also summarized automatically within Power BI, providing quick exposure when consumption jumped by volume unexpectedly or a particular machine would over-use.

Resume gap:
Staples and Intel roles ended during periods of company downsizing. Between employment at Staples and Intel, Greg focused first on family and supporting his young children. As time allowed it included coursework in data science and supply chain topics. 

Certifications and skills:
Greg's largest certification is a Supply Chain Professional from the Association for Supply Chain Management (ASCM) from 2016. Greg has also been certified as a data scientist through Intel and Springboard, and as a Machine 
Learning and AI Engineer through SuperDataScience. Greg also went through Lean Six Sigma Black Belt training while at Staples.  Other skills are in process optimization; performance metrics; data identification, extraction, expansion, preparation; machine learning and AI engineering; 
Docker; MLflow; Git, GitHub, Hugging Face; SQL, Python, VBA; Access database; Excel automation; Power BI and Tableau; logistics and efficiency; clustering; natural language processing (NLP) and sentiment analysis; 
k-nearest, linear/logistic regression, classification, decision tree, random forest, XGBoost, neural networks.
"""

resume = """
Gregory K. Gibson
Westborough, MA 01581 | 617-312-8543 | gregory.k.gibson7@gmail.com | 
github.com/gibsongGH | linkedin.com/in/gregorykgibson

MANAGER CUSTOM REPORTING & ANALYTICS SUMMARY
Data utilizer driving savings through insights, meaningful metrics, process improvements, and informative presentations. Adept at data wrangling, exploratory analysis, visualization, machine learning models, reporting automation, and managing multiple projects. Drove cross-functional coordination and process improvements through remote facilities by developing actionable comparisons. Automated production of numerous reports to remove manual efforts and potential for error, while highlighting only relevant alerts.

AREAS OF EXPERTISE
Data Analytics | Performance Metrics | Business Intelligence | Automation | Process Optimization
Operations Strategy | Forecasting | Risk Management | Stakeholder Engagement | Analyst Management

KEY ACHIEVEMENTS
•	Proven avoidance of $190M in replacement product and rework expense.
•	Effective new metrics and elimination of manual labor behind reporting management.
•	Machine learning certifications from Intel and Springboard, and Supply Chain Professional from APICS.
•	Developing analysts to management positions.

TECHNICAL SKILLS
Languages: SQL, VBA, Python.
Predictive Modeling: K-nearest, Linear/Logistic Regression, Classification, Decision Tree, Random Forest, XGBoost, Neural Networks.
Machine Learning: Clustering, Natural Language Processing (NLP), Sentiment Analysis.
Probability And Statistics: Hypothesis Testing, A/B Testing.
Tools And Methods: Advanced Excel, Access, Power BI, Tableau, MLflow, git, mining, wrangling, cleaning, analysis, visualization.
Optimization: Lean Six Sigma, APICS Certified Supply Chain Professional.

RELEVANT PROFESSIONAL EXPERIENCE
Intel, Remote	01/2022 – 01/2025
Facilities Engineer
Utilized flow meter data to improve accuracy for 70% of quarterly manual updates of chemical consumption volume by operation.
•	Maintained and added automation to many interrelated business model management systems, reducing effort, gaps and errors.
•	Highlighted increase and partnered with Design to avoid $4.5M facilities expansion to accommodate first-of-kind tools consumption of argon.

Staples, Framingham, MA	08/2003 – 02/2016
Manager Shortage Control
Drove cargo loss as a rate of sales from 0.38% to 0.07%, avoiding $190M in reshipped product and rework expense over 10 years.
•	Conceptualized Proof of Delivery and Claims database, and managed outside consultant; restitution recovered $3.2M in first year.
•	Reduced average delivery trips per order from 1.3 to 1.1 by developing reporting tools and leading a supply chain team to improve in-stock strategies, and warehousing and delivery coordination.
•	Analyzed customer complaints, leading to greater shipping carton utilization and annual savings of $2M in labor and materials.
•	Took over the Perfect Order reporting and bonus system, and reduced production time from over 1 day to 2 hours.

EDUCATION
Bachelor of Science (BSc.), Industrial Engineering & Operations Research
University of Massachusetts, Amherst

PROFESSIONAL DEVELOPMENT AND CERTIFICATIONS
Data Science Certification
Springboard, 550 hour curriculum and 1:1 industry mentorship.

Intel Machine Learning Certification
APICS Certified Supply Chain Professional
IACT Excel Master

"""

#--------------------------------------------------
# Chunking Function
#--------------------------------------------------
# --- Chunking Parameters ---
CHUNK_SIZE = 300     # Target size of each chunk in characters
OVERLAP = 30         # Number of characters shared between consecutive chunks
MIN_CHUNK_SIZE = 150 # Minimum acceptable chunk size — prevents tiny trailing chunks

def chunk_document(text, chunk_size=CHUNK_SIZE, overlap=OVERLAP, min_chunk_size=MIN_CHUNK_SIZE):
    """
    Splits a document into overlapping chunks that respect natural text boundaries.
    Priority order for where a chunk ends:
      1. Paragraph boundary (double newline)
      2. Sentence boundary (. ! ? followed by whitespace)
      3. Word boundary (any whitespace)
    Words are never split. Chunks are at least min_chunk_size characters unless the
    remaining text is shorter. Consecutive chunks share `overlap` characters of context.
    """
    chunks = []               # Accumulates the finished chunks
    start = 0                 # Index of the first character of the current chunk
    text_length = len(text)   # Total number of characters in the document
    while start < text_length:
        # ── Calculate where this chunk would ideally end ──────────────────────
        # Aim for a chunk of approximately chunk_size characters.
        target_end = start + chunk_size
        # If the target end reaches or passes the end of the document,
        # just take whatever text is left and we're done.
        if target_end >= text_length:
            remaining = text[start:].strip()  # Strip surrounding whitespace
            if remaining:                     # Skip if only whitespace remains
                chunks.append(remaining)
            break                             # No more text to process
        # ── Define the earliest acceptable end position ───────────────────────
        # We never end a chunk before this point so every chunk is at least
        # min_chunk_size characters long (barring the final leftover).
        search_floor = start + min_chunk_size
        # ── Priority 1: Paragraph boundary (\n\n) ────────────────────────────
        # Search backwards from target_end so we land as close to the target
        # size as possible while still ending at a blank line.
        para_pos = text.rfind('\n\n', search_floor, target_end + 1)
        if para_pos != -1:
            # End the chunk right after the double newline so the newlines
            # belong to the current chunk, not the next one.
            end = para_pos + 2
        else:
            # ── Priority 2: Sentence boundary (. ! ?) ────────────────────────
            # Walk backwards from target_end looking for sentence-ending
            # punctuation immediately followed by whitespace (space, newline, tab).
            end = -1  # Sentinel — will stay -1 if no sentence boundary is found
            for i in range(min(target_end, text_length - 1), search_floor - 1, -1):
                if text[i] in '.!?' and (i + 1 < text_length) and text[i + 1] in ' \n\t\r':
                    # Include the punctuation mark itself in the current chunk.
                    end = i + 1
                    break
            if end == -1:
                # ── Priority 3: Word boundary (whitespace) ────────────────────
                # Walk backwards from target_end to find any whitespace character
                # so we never slice through the middle of a word.
                end = -1  # Reset sentinel for this search
                for i in range(min(target_end, text_length - 1), search_floor - 1, -1):
                    if text[i] in ' \n\t\r':
                        # End just before the whitespace so the space is not
                        # included at the tail of the chunk.
                        end = i
                        break
                if end == -1:
                    # No boundary of any kind was found in the search window.
                    # This should only happen with pathologically long single
                    # words; fall back to a hard cut at the target position.
                    end = min(target_end, text_length)
        # ── Store the completed chunk ─────────────────────────────────────────
        chunk = text[start:end].strip()  # Remove leading/trailing whitespace
        if chunk:                        # Discard chunks that are only whitespace
            chunks.append(chunk)
        # ── Advance the start position for the next chunk ────────────────────
        # Subtract `overlap` so the next chunk re-reads the last `overlap`
        # characters of this chunk, giving the model continuity across boundaries.
        next_start = end - overlap
        # Safety guard: if subtracting overlap would not move us forward
        # (e.g. the chunk was very short), skip the overlap to avoid looping.
        if next_start <= start:
            next_start = end
        start = next_start  # Move to the start of the next chunk
    return chunks

#--------------------------------------------------
# RAG: Chunk, Embed & Store in ChromaDB
#--------------------------------------------------
documents = [
    {"text": overview, "source": "Overview"},
    {"text": projects, "source": "Projects"},
    {"text": resume, "source": "Resume"}
]

chunks = []
ids = []
metadatas = []

for doc in documents:
    # Prepare the lists
    chunks_ = chunk_document(doc["text"])
    ids_ = [str(uuid.uuid4()) for _ in range(len(chunks_))]
    metadatas_ = [{"source": doc["source"], "chunk_index": i} for i in range(len(chunks_))]
    # Add to main lists
    chunks.extend(chunks_)
    ids.extend(ids_)
    metadatas.extend(metadatas_)

# Print for logs
print(f"Created {len(chunks)} chunks:\n")
for i, chunk in enumerate(chunks):
    print(f"Chunk {i + 1} (ID: {ids[i]}, Source: {metadatas[i]['source']}, Index: {metadatas[i]['chunk_index']}, Length: {len(chunk)}):")
    print(chunk)
    print()

# Generate embeddings for all chunks
response = client.embeddings.create(
    model = "text-embedding-3-small",  
    # large does twice as many embeddings, costs more, and you must use same size for retrieval
    input = chunks
)
embeddings = [item.embedding for item in response.data]

# Verify embeddings for logs
print(f"Generated {len(embeddings)} embeddings")
print(f"Each embedding has {len(embeddings[0])} dimensions")

# Initialize ChromaDB client (persistent storage)
chroma_client = chromadb.PersistentClient(path="./chroma_db_twin")
# alternative: initialize ChromaDB client (in-memory storage)
# chroma_client = chromadb.Client()

# Get or Create + Empty the collection before adding new data (for testing purposes)
collection = chroma_client.get_or_create_collection(name="digital_twin")
if collection.get()["ids"]:
    collection.delete(collection.get()["ids"])

# Add data to the ChromaDB collection
collection.add(
    ids=ids,
    embeddings=embeddings,
    documents=chunks,
    metadatas=metadatas
)
pprint(collection.get())

#--------------------------------------------------
# Tools
#--------------------------------------------------
tools = []

pushover_user = os.getenv("PUSHOVER_USER")
pushover_token = os.getenv("PUSHOVER_TOKEN")
pushover_url = "https://api.pushover.net/1/messages.json"

# Send Pushover notification function
def send_notification(message: str):
    if pushover_user is None or pushover_token is None: # Handling of potential missing credentials
        return "Notification failed: Pushover not configured."
    payload = {"user": pushover_user, "token": pushover_token, "message": message}
    requests.post(pushover_url, data=payload)
    return f"Notification sent: {message}"

#Describe Pushover as an LLM tool for sending conversation summaries to Greg's phone
send_notification_function = {
    "name": "send_notification",
    "description": "Sends a push notification to the real Greg.  Use this when: \
            1) Someone wants to get in touch, hire, or collaborate\
            - ask for their name and contact details first, then send notification to Greg with the name and contact details. \
            2) You don't know the answer to a question about Greg - send AUTOMATICALLY without asking, include the question so he can add this info later.",
    "parameters": {
        "type": "object",
        "properties": {
            "message": {"type": "string", "description": "A brief summary of the conversation to send to Greg's phone"}
        },
        "required": ["message"]
    }
}

#Add Pushover to list of tools for the LLM to use
tools.append({"type": "function", "function": send_notification_function})

#Simulates rolling a six-sided die
def dice_roll():
    result = random.randint(1, 6)
    return result

#Description of the dice_roll function for the LLM
roll_dice_function = {
    "name": "dice_roll",
    "description": "Simulates rolling a single six-sided die and returns the result.  Use this when the user wants to roll a die for games, decisions, or random number generation.",
    "parameters": {
        "type": "object",
        "properties": {},
        "required": []
    }
}

#Add the new function to the list of tools
tools.append({"type": "function", "function": roll_dice_function})

#--------------------------------------------------
# Tool Handler
#--------------------------------------------------
def handle_tool_calls(tool_calls):
    tool_call_results = []
    
    for tool_call in tool_calls:
        function_name = tool_call.function.name
        args = json.loads(tool_call.function.arguments)
        #print(f"Calling function {function_name}")

        # Route to the appropriate function based on function_name
        if function_name == "send_notification":
            content = send_notification(args["message"])
        elif function_name == "dice_roll":
            content = f"Rolled: {dice_roll()}"
        else:
            content = f"Unknown function: {function_name}"

        tool_call_results.append({
            "role": "tool",
            "content": content,
            "tool_call_id": tool_call.id
        })
        
    return tool_call_results

#--------------------------------------------------
# System Message
#--------------------------------------------------
system_message = """You are a digital twin of Greg Gibson, an AI and Machine Learning engineer.  When people talk to you,
you respond AS Greg - in first person, using his voice, personality, and knowledge.

Important: do not make things up.  If you don't know an answer, say you don't know.
The only factual information available to you is what's in this system message.
You cannot get any more facts about Greg from the internet or make them up.

IMPORTANT: Whenever you don't know something about Greg, 
ALWAYS use the send_notification tool to alert the real Greg - do this automatically without asking the user.

If asked about recent projects or accomplishments, discuss my solo projects: AI Article Writer, my "digital twin", the Netflix RAG of their culture documents, and CardioSentinel heart attack prediction.
Do not mention presentations with these topics.
"""

#--------------------------------------------------
# Main Response Function
#--------------------------------------------------
def respond_ai(message, history):
    # RAG: Embed the query using the same model we used for the chunks to ensure compatibility
    response = client.embeddings.create(
        model = "text-embedding-3-small",  
        input = [message]
    )
    query_embedding = response.data[0].embedding

    # Search ChromaDB
    results = collection.query(
        query_embeddings=[query_embedding],
        n_results=3
    )   

    # RAG: Stitch retrieved chunks together to create the context for the response
    context = "\n---\n".join(results["documents"][0])
    
    # Print logs for debugging
    print("\n===========================\n")
    print(f"User message:\n{message}\n")
    print("***Retrieved Chunks:")
    for a, b in zip(results["documents"][0], results["metadatas"][0]):  #a chunk, b metadata
        print("-------------------")
        print(f"<<Document: {b['source']} -- Chunk {b['chunk_index']}>>:\n{a}\n")

    # Update system message with context (for this conversatioo turn)
    system_message_enhanced = system_message + "\n\nContext:\n" + context
    
    # Build messages for this turn
    messages = [{"role": "system", "content": system_message_enhanced}] + history + [{"role": "user", "content": message}]

    # Call LLM
    response = client.chat.completions.create(
        model="gpt-4.1-mini",
        messages=messages,
        tools=tools,
    )
    message = response.choices[0].message  # get message object, not just .content

    # Step 2: Check if model wants to call a tool
    while message.tool_calls:
        # pprint(message.tool_calls)
        
        tool_result = handle_tool_calls(message.tool_calls) # Whole list of tool calls
        messages.append(message) # response from LLM with tool_calls but no content
        messages.extend(tool_result) # one result per tool call

        response = client.chat.completions.create(
            model="gpt-4.1-mini",
            messages=messages,
            tools=tools
        )
        message = response.choices[0].message

    return(message.content)

#--------------------------------------------------
# Launch Gradio App
#--------------------------------------------------
gr.ChatInterface(
    fn=respond_ai,
    title="Greg's Digital Twin",
    chatbot=gr.Chatbot(avatar_images=(None, "Headshot.jpeg")),
    description="Chat with an AI version of Greg Gibson.  Ask about his experience, projects, or just say hi!",
    examples=["What's your background?", "What projects have you worked on?", "Roll some dice and tell me the sum!", "Let's collaborate on an AI project idea!"]
    ).launch()